<?php

use TechRaj\DeleteOrders\Block\Adminhtml\System\Config\Manually;

/** @var Manually $block */ ?>

<button id="rajdeleteorders_run_manually" title="Run Manually" type="button" class="primary">
    <span><?= __('Run Manually') ?></span>
    </span></button>
<div class="rajdeleteorders_popup_confirm"></div>

<style>
    button#mpdeleteorders_run_manually {
        width: 94%;
    }
</style>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm',
        'mage/translate',
    ], function ($, confirm, $t) {
        $("#rajdeleteorders_run_manually").on('click', function () {
            confirm({
                content: $t('Are you sure to run manually?'),
                actions: {
                    /** @inheritdoc */
                    confirm: function () {
                        window.location.href = "<?= $block->getUrl('sales/delete/manually', ['_current' => true, '_use_rewrite' => true]) ?>";
                    }
                }
            });
        });
    })
</script>
